language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - scons
    update: true
  homebrew:
    packages:
      - scons
    update: true
script:
  - scons check
after_failure:
  - cat check.log
